version: '3.8'

services:
  caddy:
    image: "caddy:latest"
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Mount our Caddyfile into the container
      - ./Caddyfile:/etc/caddy/Caddyfile
      # Mount a volume to store automatic HTTPS certs/keys
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    depends_on:
      - frontend
      - backend


  backend:
    build: 
      context: ./onitama-server
      dockerfile: Dockerfile
    container_name: go-backend
    ports:
      - "8080:8080"
    # You can set environment variables here if needed
    #environment:
      # Example: "KEY=VALUE"
      # API_KEY: "your-api-key"
      # ...
    # If you need volumes, you can define them here (optional)
    # volumes:
    #   - ./backend:/app

  frontend:
    build: 
      context: ./onitama-client
      dockerfile: Dockerfile
    container_name: next-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_BACKEND_URL: "localhost:8080"  # If your frontend needs to call the backend in Docker

volumes:
  caddy_data:
  caddy_config:

