import type { Metadata } from "next";
import { Geist, Geist_Mono, Joti_One } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const jotiOne = Joti_One({
	weight: "400",
  variable: "--font-joti-one",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon shortcut" href="/Player1-captain.png" />
      <body className={`${geistSans.variable} ${geistMono.variable} ${jotiOne.variable}`}>
        {children}
      </body>
    </html>
  );
}
